=== hmcts/pre-api/src/test/resources/edit-requests/existing/schema-edited-recording.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Recording",
  "definitions": {
    "Recording": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "parent_recording_id": {
          "type": "string",
          "format": "uuid"
        },
        "version": {
          "type": "integer"
        },
        "total_version_count": {
          "type": "integer"
        },
        "edit_instructions": {
          "type": "string"
        },
        "edit_requests": {
          "type": "array",
          "items": {}
        },
        "filename": {
          "type": "string"
        },
        "duration": {
          "type": "string"
        },
        "capture_session": {
          "$ref": "#/definitions/CaptureSession"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "case_id": {
          "type": "string",
          "format": "uuid"
        },
        "case_reference": {
          "type": "string"
        },
        "is_test_case": {
          "type": "boolean"
        },
        "participants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Participant"
          }
        }
      },
      "required": [
        "capture_session",
        "case_id",
        "case_reference",
        "created_at",
        "duration",
        "edit_instructions",
        "edit_requests",
        "filename",
        "id",
        "is_test_case",
        "parent_recording_id",
        "participants",
        "total_version_count",
        "version"
      ],
      "title": "Recording"
    },
    "CaptureSession": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "booking_id": {
          "type": "string",
          "format": "uuid"
        },
        "origin": {
          "type": "string"
        },
        "ingest_address": {
          "type": "string"
        },
        "live_output_url": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        },
        "started_at": {
          "type": "string",
          "format": "date-time"
        },
        "started_by_user_id": {
          "type": "string",
          "format": "uuid"
        },
        "finished_at": {
          "type": "string",
          "format": "date-time"
        },
        "finished_by_user_id": {
          "type": "string",
          "format": "uuid"
        },
        "status": {
          "type": "string"
        },
        "court_name": {
          "type": "string"
        },
        "case_state": {
          "type": "string"
        }
      },
      "required": [
        "booking_id",
        "case_state",
        "court_name",
        "finished_at",
        "finished_by_user_id",
        "id",
        "ingest_address",
        "live_output_url",
        "origin",
        "started_at",
        "started_by_user_id",
        "status"
      ],
      "title": "CaptureSession"
    },
    "Participant": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "participant_type": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "modified_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "created_at",
        "first_name",
        "id",
        "last_name",
        "modified_at",
        "participant_type"
      ],
      "title": "Participant"
    }
  }
}

=== hmcts/pre-api/src/test/resources/edit-requests/existing/sample-recording-2-edits-not-displayed.json
{
  "id": "ed360496-e35f-4c71-9f05-e6c4ce843370",
  "parent_recording_id": "8c73cf3e-efc5-485b-91b0-7ba62f3985b5",
  "version": 7,
  "total_version_count": 7,
  "edit_instructions": "{\"ffmpegInstructions\": [{\"end\": 600, \"start\": 0}, {\"end\": 2400, \"start\": 1200}, {\"end\": 3955, \"start\": 2700}], \"requestedInstructions\": [{\"end\": 1200, \"start\": 600, \"reason\": \"Removing 10 minutes from version 1\", \"end_of_cut\": \"00:20:00\", \"start_of_cut\": \"00:10:00\"}, {\"end\": 2700, \"start\": 2400, \"reason\": \"Also removing 5 minutes from version 1\", \"end_of_cut\": \"00:45:00\", \"start_of_cut\": \"00:40:00\"}]}",
  "edit_requests": [],
  "filename": "ed360496-e35f-4c71-9f05-e6c4ce84_1280x720_4500k.mp4",
  "duration": "PT50M55.7S",
  "capture_session": {
    "id": "bb5ec935-5bb6-43ba-8ec5-241aba1d1b52",
    "booking_id": "15cfbbed-53bd-41b5-ab57-0962ab919f18",
    "origin": "PRE",
    "ingest_address": "rtmps://in-890f8537-c5d4-4b81-bb69-31fa36e21e26.uksouth.streaming.mediakind.com:2935/eca9b219-03c4-4e70-b768-c513122b859a",
    "live_output_url": "https://ep-default-live-pre-mediakind-stg.uksouth.streaming.mediakind.com/bb5ec9355bb643ba8ec5241aba1d1b52/index.qfm/manifest(format=m3u8-cmaf)",
    "started_at": "2025-05-27T08:55:58.931Z",
    "started_by_user_id": "f8750aa0-ecf3-ec11-bb3c-0022481b1f95",
    "finished_at": "2025-05-27T10:54:16.279Z",
    "finished_by_user_id": "f8750aa0-ecf3-ec11-bb3c-0022481b1f95",
    "status": "RECORDING_AVAILABLE",
    "court_name": "Leeds Youth",
    "case_state": "OPEN"
  },
  "created_at": "2025-08-26T11:09:49.447Z",
  "case_id": "eb0d9ede-6c96-4819-8d70-cdfc630e7c1f",
  "case_reference": "STG-AUTOEDIT2",
  "is_test_case": false,
  "participants": [
    {
      "id": "c5f269be-0d57-408d-9fde-51e0f221138e",
      "participant_type": "DEFENDANT",
      "first_name": "Test",
      "last_name": "Test2",
      "created_at": "2025-05-27T08:53:32.855Z",
      "modified_at": "2025-05-27T08:53:32.831Z"
    },
    {
      "id": "f442ca19-da72-4d23-a239-a27d6bb9b4c8",
      "participant_type": "WITNESS",
      "first_name": "Test2",
      "last_name": "",
      "created_at": "2025-05-27T08:53:32.851Z",
      "modified_at": "2025-05-27T08:53:32.825Z"
    }
  ]
}

=== hmcts/pre-api/src/test/resources/edit-requests/existing/sample-edited-recording-testno2.json
{
  "id": "b817685b-0155-4946-b09e-6bd369ef0381",
  "parent_recording_id": "e0912d46-cded-4757-9367-2d8b3f81693f",
  "version": 4,
  "total_version_count": 4,
  "edit_instructions": "{\"editRequestId\": \"f264f9cb-0203-4fa6-9234-b6efec06819e\", \"editInstructions\": {\"ffmpegInstructions\": [{\"end\": 180, \"start\": 0}, {\"end\": 733, \"start\": 300}], \"requestedInstructions\": [{\"end\": 300, \"start\": 180, \"reason\": \"Removing 2 minutes\", \"end_of_cut\": \"00:05:00\", \"start_of_cut\": \"00:03:00\"}]}}",
  "edit_requests": [],
  "filename": "b817685b-0155-4946-b09e-6bd369ef_1280x720_4500k.mp4",
  "duration": "PT10M15.2S",
  "capture_session": {
    "id": "2a6d504d-2c72-4f18-aad4-d08505caa304",
    "booking_id": "9e823ccb-cb20-43ba-a430-56dbc6190b7c",
    "origin": "PRE",
    "ingest_address": "rtmps://in-2c40ef17-caa6-4caf-8268-775ab8c49e3d.uksouth.streaming.mediakind.com:2935/1ccdd12f-7114-4315-9b1e-243bd721cba2",
    "live_output_url": "https://ep-default-live-pre-mediakind-stg.uksouth.streaming.mediakind.com/2a6d504d2c724f18aad4d08505caa304/index.qfm/manifest(format=m3u8-cmaf)",
    "started_at": "2025-06-26T10:01:37.688Z",
    "started_by_user_id": "8da77965-acec-4256-b695-509924a11f06",
    "finished_at": "2025-06-26T10:20:34.489Z",
    "finished_by_user_id": "8da77965-acec-4256-b695-509924a11f06",
    "status": "RECORDING_AVAILABLE",
    "court_name": "102 Petty France",
    "case_state": "OPEN"
  },
  "created_at": "2026-02-24T10:42:40.059Z",
  "case_id": "368bc646-32eb-4e3a-9af3-aeac32f86630",
  "case_reference": "TEST-NO-2",
  "is_test_case": false,
  "participants": [
    {
      "id": "d863d7b5-63e4-4fad-b80c-6fe1848191c4",
      "participant_type": "DEFENDANT",
      "first_name": "Komal",
      "last_name": "Dabhi",
      "created_at": "2025-06-26T10:00:17.576Z",
      "modified_at": "2025-06-26T10:00:17.556Z"
    },
    {
      "id": "eb518f93-9db5-40eb-a538-ac95df9a5b9a",
      "participant_type": "WITNESS",
      "first_name": "Simon",
      "last_name": "",
      "created_at": "2025-06-26T10:00:17.567Z",
      "modified_at": "2025-06-26T10:00:17.549Z"
    }
  ]
}
