=== hmcts/pre-api/src/test/resources/edit-requests/existing/schema-parent-recording.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Recording",
  "definitions": {
    "Recording": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "version": {
          "type": "integer"
        },
        "total_version_count": {
          "type": "integer"
        },
        "edit_status": {
          "type": "string"
        },
        "edit_requests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/EditRequest"
          }
        },
        "capture_session": {
          "$ref": "#/definitions/CaptureSession"
        },
        "filename": {
          "type": "string"
        },
        "duration": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "case_id": {
          "type": "string",
          "format": "uuid"
        },
        "case_reference": {
          "type": "string"
        },
        "is_test_case": {
          "type": "boolean"
        },
        "participants": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Participant"
          }
        }
      },
      "required": [
        "capture_session",
        "case_id",
        "case_reference",
        "created_at",
        "duration",
        "edit_requests",
        "edit_status",
        "filename",
        "id",
        "is_test_case",
        "participants",
        "total_version_count",
        "version"
      ],
      "title": "Recording"
    },
    "EditRequest": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "edit_instruction": {
          "$ref": "#/definitions/EditInstruction"
        },
        "status": {
          "type": "string"
        },
        "created_by_id": {
          "type": "string",
          "format": "uuid"
        },
        "created_by": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "modified_at": {
          "type": "string",
          "format": "date-time"
        },
        "started_at": {
          "type": "string",
          "format": "date-time"
        },
        "finished_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "created_at",
        "created_by",
        "created_by_id",
        "edit_instruction",
        "id",
        "modified_at",
        "status"
      ],
      "title": "EditRequest"
    },
    "EditInstruction": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ffmpegInstructions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/FfmpegInstruction"
          }
        },
        "requestedInstructions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RequestedInstruction"
          }
        }
      },
      "required": [
        "ffmpegInstructions",
        "requestedInstructions"
      ],
      "title": "EditInstruction"
    },
    "FfmpegInstruction": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "start": {
          "type": "integer"
        },
        "end": {
          "type": "integer"
        }
      },
      "required": [
        "end",
        "start"
      ],
      "title": "FfmpegInstruction"
    },
    "RequestedInstruction": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "start_of_cut": {
          "type": "string",
          "format": "time"
        },
        "end_of_cut": {
          "type": "string",
          "format": "time"
        },
        "reason": {
          "type": "string"
        },
        "start": {
          "type": "integer"
        },
        "end": {
          "type": "integer"
        }
      },
      "required": [
        "end",
        "end_of_cut",
        "reason",
        "start",
        "start_of_cut"
      ],
      "title": "RequestedInstruction"
    },
    "CaptureSession": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "booking_id": {
          "type": "string",
          "format": "uuid"
        },
        "origin": {
          "type": "string"
        },
        "ingest_address": {
          "type": "string"
        },
        "live_output_url": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": [
            "https"
          ]
        },
        "started_at": {
          "type": "string",
          "format": "date-time"
        },
        "started_by_user_id": {
          "type": "string",
          "format": "uuid"
        },
        "finished_at": {
          "type": "string",
          "format": "date-time"
        },
        "finished_by_user_id": {
          "type": "string",
          "format": "uuid"
        },
        "status": {
          "type": "string"
        },
        "court_name": {
          "type": "string"
        },
        "case_state": {
          "type": "string"
        }
      },
      "required": [
        "booking_id",
        "case_state",
        "court_name",
        "finished_at",
        "finished_by_user_id",
        "id",
        "ingest_address",
        "live_output_url",
        "origin",
        "started_at",
        "started_by_user_id",
        "status"
      ],
      "title": "CaptureSession"
    },
    "Participant": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "participant_type": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "modified_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "created_at",
        "first_name",
        "id",
        "last_name",
        "modified_at",
        "participant_type"
      ],
      "title": "Participant"
    }
  }
}

=== hmcts/pre-api/src/test/resources/edit-requests/existing/sample-recording-parent-testno2.json
{
  "id": "e0912d46-cded-4757-9367-2d8b3f81693f",
  "version": 1,
  "total_version_count": 4,
  "edit_requests": [
    {
      "id": "d3a1f270-9037-4782-8e73-462e2e0b7340",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:00:01",
            "end_of_cut": "00:00:02",
            "reason": "test",
            "start": 1,
            "end": 2
          },
          {
            "start_of_cut": "00:03:00",
            "end_of_cut": "00:05:00",
            "reason": "Removing 2 minutes",
            "start": 180,
            "end": 300
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 1
          },
          {
            "start": 2,
            "end": 180
          },
          {
            "start": 300,
            "end": 733
          }
        ]
      },
      "status": "DRAFT",
      "created_by_id": "c56e379e-88cc-417c-801a-8647b82825c9",
      "created_by": "Lydia Ralph (DEV)",
      "created_at": "2026-02-27T14:25:31.228Z",
      "modified_at": "2026-02-27T14:25:31.223Z"
    },
    {
      "id": "91746e31-5d54-4b94-9b5e-61df2637c108",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:00:01",
            "end_of_cut": "00:00:02",
            "reason": "test",
            "start": 1,
            "end": 2
          },
          {
            "start_of_cut": "00:03:00",
            "end_of_cut": "00:05:00",
            "reason": "Removing 2 minutes",
            "start": 180,
            "end": 300
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 1
          },
          {
            "start": 2,
            "end": 180
          },
          {
            "start": 300,
            "end": 733
          }
        ]
      },
      "status": "DRAFT",
      "created_by_id": "c56e379e-88cc-417c-801a-8647b82825c9",
      "created_by": "Lydia Ralph (DEV)",
      "created_at": "2026-02-27T14:25:13.784Z",
      "modified_at": "2026-02-27T14:25:13.773Z"
    },
    {
      "id": "f264f9cb-0203-4fa6-9234-b6efec06819e",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:03:00",
            "end_of_cut": "00:05:00",
            "reason": "Removing 2 minutes",
            "start": 180,
            "end": 300
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 180
          },
          {
            "start": 300,
            "end": 733
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2026-02-24T10:40:36.066Z",
      "finished_at": "2026-02-24T10:42:39.851Z",
      "created_by_id": "8da77965-acec-4256-b695-509924a11f06",
      "created_by": "Komal Dabhi (DEV)",
      "created_at": "2026-02-24T10:39:01.665Z",
      "modified_at": "2026-02-24T10:42:40.050Z"
    },
    {
      "id": "aa5e4e2f-0169-48af-a084-5f4cb00d2ec9",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:05:00",
            "end_of_cut": "00:07:59",
            "reason": "Removing almost 3 minutes",
            "start": 300,
            "end": 479
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 300
          },
          {
            "start": 479,
            "end": 733
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-12-15T13:30:37.154Z",
      "finished_at": "2025-12-15T13:32:22.546Z",
      "created_by_id": "8da77965-acec-4256-b695-509924a11f06",
      "created_by": "Komal Dabhi (DEV)",
      "created_at": "2025-12-15T13:27:36.640Z",
      "modified_at": "2025-12-18T12:05:52.098Z"
    },
    {
      "id": "0d71a6de-7db0-4e04-8611-f288d7e26a7d",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:00:00",
            "end_of_cut": "00:01:00",
            "reason": "I don’t want this",
            "start": 0,
            "end": 60
          },
          {
            "start_of_cut": "00:01:01",
            "end_of_cut": "00:02:00",
            "reason": "",
            "start": 61,
            "end": 120
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 60,
            "end": 61
          },
          {
            "start": 120,
            "end": 733
          }
        ]
      },
      "status": "PROCESSING",
      "started_at": "2025-12-15T10:11:22.530Z",
      "created_by_id": "c56e379e-88cc-417c-801a-8647b82825c9",
      "created_by": "Lydia Ralph (DEV)",
      "created_at": "2025-12-15T10:09:20.579Z",
      "modified_at": "2025-12-15T10:11:22.544Z"
    }
  ],
  "edit_status": "DRAFT",
  "capture_session": {
    "id": "2a6d504d-2c72-4f18-aad4-d08505caa304",
    "booking_id": "9e823ccb-cb20-43ba-a430-56dbc6190b7c",
    "origin": "PRE",
    "ingest_address": "rtmps://in-2c40ef17-caa6-4caf-8268-775ab8c49e3d.uksouth.streaming.mediakind.com:2935/1ccdd12f-7114-4315-9b1e-243bd721cba2",
    "live_output_url": "https://ep-default-live-pre-mediakind-stg.uksouth.streaming.mediakind.com/2a6d504d2c724f18aad4d08505caa304/index.qfm/manifest(format=m3u8-cmaf)",
    "started_at": "2025-06-26T10:01:37.688Z",
    "started_by_user_id": "8da77965-acec-4256-b695-509924a11f06",
    "finished_at": "2025-06-26T10:20:34.489Z",
    "finished_by_user_id": "8da77965-acec-4256-b695-509924a11f06",
    "status": "RECORDING_AVAILABLE",
    "court_name": "102 Petty France",
    "case_state": "OPEN"
  },
  "filename": "2a6d504d2c724f18aad4d08505caa304_1280x720_4500k.mp4",
  "duration": "PT12M13.5S",
  "created_at": "2025-06-26T10:23:23.276Z",
  "case_id": "368bc646-32eb-4e3a-9af3-aeac32f86630",
  "case_reference": "TEST-NO-2",
  "is_test_case": false,
  "participants": [
    {
      "id": "d863d7b5-63e4-4fad-b80c-6fe1848191c4",
      "participant_type": "DEFENDANT",
      "first_name": "Komal",
      "last_name": "Dabhi",
      "created_at": "2025-06-26T10:00:17.576Z",
      "modified_at": "2025-06-26T10:00:17.556Z"
    },
    {
      "id": "eb518f93-9db5-40eb-a538-ac95df9a5b9a",
      "participant_type": "WITNESS",
      "first_name": "Simon",
      "last_name": "",
      "created_at": "2025-06-26T10:00:17.567Z",
      "modified_at": "2025-06-26T10:00:17.549Z"
    }
  ]
}

=== hmcts/pre-api/src/test/resources/edit-requests/existing/sample-recording-parent-stgautoedit2.json
{
  "id": "8c73cf3e-efc5-485b-91b0-7ba62f3985b5",
  "version": 1,
  "total_version_count": 7,
  "edit_requests": [
    {
      "id": "31de179a-f35e-41a9-a5c1-b406f824f13b",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:00:00",
            "end_of_cut": "00:40:00",
            "reason": "Remove first 40 minutes",
            "start": 0,
            "end": 2400
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 2400,
            "end": 3955
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-05-29T17:29:56.611Z",
      "finished_at": "2025-05-29T17:37:12.680Z",
      "created_by_id": "7a36422a-6c2e-418d-87de-d914b9accf2a",
      "created_by": "Cristiane Marsilio",
      "created_at": "2025-05-29T17:01:35.039Z",
      "modified_at": "2025-05-29T17:37:12.700Z"
    },
    {
      "id": "a8a92cdf-11d8-4eee-8ab8-e4b604db6200",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:15:00",
            "end_of_cut": "00:20:00",
            "reason": "Remove alarm test-version5",
            "start": 900,
            "end": 1200
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 900
          },
          {
            "start": 1200,
            "end": 3955
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-05-28T11:36:31.362Z",
      "finished_at": "2025-05-28T11:50:29.397Z",
      "created_by_id": "7a36422a-6c2e-418d-87de-d914b9accf2a",
      "created_by": "Cristiane Marsilio",
      "created_at": "2025-05-28T11:24:13.277Z",
      "modified_at": "2025-05-28T11:50:29.424Z"
    },
    {
      "id": "f30d9e9d-787d-4878-aca8-9ca0ed7149a3",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:15:00",
            "end_of_cut": "00:20:00",
            "reason": "Remove alarm test-version4",
            "start": 900,
            "end": 1200
          },
          {
            "start_of_cut": "00:40:00",
            "end_of_cut": "01:00:00",
            "reason": "Also removing this-version4",
            "start": 2400,
            "end": 3600
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 900
          },
          {
            "start": 1200,
            "end": 2400
          },
          {
            "start": 3600,
            "end": 3955
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-05-28T11:25:37.250Z",
      "finished_at": "2025-05-28T11:35:49.990Z",
      "created_by_id": "7a36422a-6c2e-418d-87de-d914b9accf2a",
      "created_by": "Cristiane Marsilio",
      "created_at": "2025-05-28T11:21:44.131Z",
      "modified_at": "2025-05-28T11:35:50.018Z"
    },
    {
      "id": "606cbba7-483d-4cac-9112-5f9fba4eaacf",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:15:00",
            "end_of_cut": "00:20:00",
            "reason": "Remove alarm test-version3",
            "start": 900,
            "end": 1200
          },
          {
            "start_of_cut": "00:40:00",
            "end_of_cut": "00:50:00",
            "reason": "Also removing this-version3",
            "start": 2400,
            "end": 3000
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 900
          },
          {
            "start": 1200,
            "end": 2400
          },
          {
            "start": 3000,
            "end": 3955
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-05-27T16:55:38.158Z",
      "finished_at": "2025-05-27T17:07:57.423Z",
      "created_by_id": "7a36422a-6c2e-418d-87de-d914b9accf2a",
      "created_by": "Cristiane Marsilio",
      "created_at": "2025-05-27T16:52:54.984Z",
      "modified_at": "2025-05-27T17:07:57.446Z"
    },
    {
      "id": "02801650-d08a-41a5-88f8-da9586f6b28d",
      "edit_instruction": {
        "requestedInstructions": [
          {
            "start_of_cut": "00:02:00",
            "end_of_cut": "00:12:00",
            "reason": "Remove alarm test",
            "start": 120,
            "end": 720
          },
          {
            "start_of_cut": "00:30:00",
            "end_of_cut": "00:50:00",
            "reason": "Also removing this",
            "start": 1800,
            "end": 3000
          }
        ],
        "ffmpegInstructions": [
          {
            "start": 0,
            "end": 120
          },
          {
            "start": 720,
            "end": 1800
          },
          {
            "start": 3000,
            "end": 3955
          }
        ]
      },
      "status": "COMPLETE",
      "started_at": "2025-05-27T14:30:39.858Z",
      "finished_at": "2025-05-27T14:39:55.425Z",
      "created_by_id": "7a36422a-6c2e-418d-87de-d914b9accf2a",
      "created_by": "Cristiane Marsilio",
      "created_at": "2025-05-27T14:27:39.208Z",
      "modified_at": "2025-05-27T14:39:55.456Z"
    }
  ],
  "edit_status": "COMPLETE",
  "capture_session": {
    "id": "bb5ec935-5bb6-43ba-8ec5-241aba1d1b52",
    "booking_id": "15cfbbed-53bd-41b5-ab57-0962ab919f18",
    "origin": "PRE",
    "ingest_address": "rtmps://in-890f8537-c5d4-4b81-bb69-31fa36e21e26.uksouth.streaming.mediakind.com:2935/eca9b219-03c4-4e70-b768-c513122b859a",
    "live_output_url": "https://ep-default-live-pre-mediakind-stg.uksouth.streaming.mediakind.com/bb5ec9355bb643ba8ec5241aba1d1b52/index.qfm/manifest(format=m3u8-cmaf)",
    "started_at": "2025-05-27T08:55:58.931Z",
    "started_by_user_id": "f8750aa0-ecf3-ec11-bb3c-0022481b1f95",
    "finished_at": "2025-05-27T10:54:16.279Z",
    "finished_by_user_id": "f8750aa0-ecf3-ec11-bb3c-0022481b1f95",
    "status": "RECORDING_AVAILABLE",
    "court_name": "Leeds Youth",
    "case_state": "OPEN"
  },
  "filename": "bb5ec9355bb643ba8ec5241aba1d1b52_1280x720_4500k.mp4",
  "duration": "PT1H5M55.9S",
  "created_at": "2025-05-27T10:59:41.027Z",
  "case_id": "eb0d9ede-6c96-4819-8d70-cdfc630e7c1f",
  "case_reference": "STG-AUTOEDIT2",
  "is_test_case": false,
  "participants": [
    {
      "id": "c5f269be-0d57-408d-9fde-51e0f221138e",
      "participant_type": "DEFENDANT",
      "first_name": "Test",
      "last_name": "Test2",
      "created_at": "2025-05-27T08:53:32.855Z",
      "modified_at": "2025-05-27T08:53:32.831Z"
    },
    {
      "id": "f442ca19-da72-4d23-a239-a27d6bb9b4c8",
      "participant_type": "WITNESS",
      "first_name": "Test2",
      "last_name": "",
      "created_at": "2025-05-27T08:53:32.851Z",
      "modified_at": "2025-05-27T08:53:32.825Z"
    }
  ]
}
